// This file is generated by GoAdmin CLI adm.
package tables

import (
	"fmt"
	"github.com/huyrun/go-admin/modules/db"
	"github.com/huyrun/go-admin/plugins/admin/modules/table"
	template2 "github.com/huyrun/go-admin/template"
	"gorm.io/gorm"
	"html/template"
	"project/utils"
)

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "entity_comments" => /admin/info/entity_comments
// "entity_tags" => /admin/info/entity_tags
// "categories" => /admin/info/categories
// "entities" => /admin/info/entities
// "activities" => /admin/info/activities
// "goose_db_version" => /admin/info/goose_db_version
// "liked_entities" => /admin/info/liked_entities
// "user_relationships" => /admin/info/user_relationships
// "saved_entities" => /admin/info/saved_entities
// "wishes" => /admin/info/wishes
// "wish_stories" => /admin/info/wish_stories
// "tags" => /admin/info/tags
// "users" => /admin/info/users
//
// example end
func NewGenerators(db *gorm.DB, conn db.Connection) (map[string]table.Generator, error) {
	userTable, err := NewUserTable(db, conn)
	if err != nil {
		return nil, err
	}
	activityTable, err := NewActivityTable(db, conn)
	if err != nil {
		return nil, err
	}
	entityCommentsTable, err := NewEntityCommentsTable(db, conn)
	if err != nil {
		return nil, err
	}
	likedEntitiesTable, err := NewLikedEntitiesTable(db, conn)
	if err != nil {
		return nil, err
	}
	savedEntitiesTable, err := NewSavedEntitiesTable(db, conn)
	if err != nil {
		return nil, err
	}
	userRelationshipsTable, err := NewUserRelationshipsTable(db, conn)
	if err != nil {
		return nil, err
	}

	return map[string]table.Generator{
		"entity_comments":    entityCommentsTable.GetEntityCommentsTable,
		"entity_tags":        GetEntitytagsTable,
		"categories":         GetCategoriesTable,
		"entities":           GetEntitiesTable,
		"activities":         activityTable.GetActivitiesTable,
		"goose_db_version":   GetGoosedbversionTable,
		"liked_entities":     likedEntitiesTable.GetLikedEntitiesTable,
		"user_relationships": userRelationshipsTable.GetUserRelationshipsTable,
		"saved_entities":     savedEntitiesTable.GetSavedEntitiesTable,
		"wishes":             GetWishesTable,
		"wish_stories":       GetWishstoriesTable,
		"tags":               GetTagsTable,
		"users":              userTable.GetUsersTable,

		// generators end
	}, nil
}

var (
	cssTableNoWrap = template.CSS(`table{white-space: nowrap;}`)
)

func linkToOtherTable(tableName, value string) template.HTML {
	return template2.Default().
		Link().
		SetURL(fmt.Sprintf("/admin/info/%s/detail?__goadmin_detail_pk=%s", tableName, value)).
		SetContent(template.HTML(value)).
		OpenInNewTab().
		SetTabTitle(template.HTML(fmt.Sprintf("%s Detail(%s)", utils.CapitalizeFirst(tableName), value))).
		GetContent()
}
