// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "entity_comments" => /admin/info/entity_comments
// "entity_tags" => /admin/info/entity_tags
// "categories" => /admin/info/categories
// "entities" => /admin/info/entities
// "activities" => /admin/info/activities
// "goose_db_version" => /admin/info/goose_db_version
// "liked_entities" => /admin/info/liked_entities
// "user_relationships" => /admin/info/user_relationships
// "saved_entities" => /admin/info/saved_entities
// "wishes" => /admin/info/wishes
// "wish_stories" => /admin/info/wish_stories
// "tags" => /admin/info/tags
// "users" => /admin/info/users
//
// example end
var Generators = map[string]table.Generator{

	"entity_comments":    GetEntitycommentsTable,
	"entity_tags":        GetEntitytagsTable,
	"categories":         GetCategoriesTable,
	"entities":           GetEntitiesTable,
	"activities":         GetActivitiesTable,
	"goose_db_version":   GetGoosedbversionTable,
	"liked_entities":     GetLikedentitiesTable,
	"user_relationships": GetUserrelationshipsTable,
	"saved_entities":     GetSavedentitiesTable,
	"wishes":             GetWishesTable,
	"wish_stories":       GetWishstoriesTable,
	"tags":               GetTagsTable,
	"users":              GetUsersTable,

	// generators end
}
